module.exports = `
  type WorkTotal {
    _id: String
    totalDays: Float
    totalSalary: Float
  }

  type Query {
    allWorkTotals: [WorkTotal]
    workTotal(_id:String!):WorkTotal
  }

  type Mutation {
    addWorkTotals(
      _id:String!,
    ):WorkTotal
  }
`