module.exports = `
  type WorkTotal {
    _id: String
    totalDays: Float
    totalSalary: Float
  }

  type WorkOption {
    _id: String,
    name: String,
    location: String
    startHour: Float,
    endHour: Float,
    salaryPerHour: Float
  }

  type User {
    _id: String
    name: String
    email: String!
    jwt: String
  }

  type Query {
    allWorkTotals: [WorkTotal]
    workTotal(_id:String!):WorkTotal
    allWorkOptions: [WorkOption]
    workOption(_id:String!):WorkOption
    allUsers: [User]
  }

  type Mutation {
    addWorkTotals(
      _id:String!,
    ):WorkTotal
    register(
      name: String!
      email: String!
      password: String!
    ):User
    login(
      email: String!
      password: String!
    ):User
  }
`