module.exports = `
  type WorkTotal {
    _id: String
    totalDays: Float
    totalSalary: Float
  }

  type WorkOption {
    _id: String,
    name: String,
    location: String
    startHour: Float,
    endHour: Float,
    salaryPerHour: Float
  }

  type Query {
    allWorkTotals: [WorkTotal]
    workTotal(_id:String!):WorkTotal
    allWorkOptions: [WorkOption]
    workOption(_id:String!):WorkOption
  }

  type Mutation {
    addWorkTotals(
      _id:String!,
    ):WorkTotal
  }
`